on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.9"
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e lptm4c123gh6pm
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: Firmware
        path: .pio/build/lptm4c123gh6pm/firmware.bin